# Generated by Django 4.0.5 on 2022-06-30 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storylineapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('unitNumber', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BodyScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('sensation', models.CharField(max_length=200)),
                ('dateTime', models.DateTimeField()),
                ('intensity', models.IntegerField()),
                ('frontOrBack', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Clinician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('storylineNetwork', models.CharField(max_length=200)),
                ('activityStatus', models.BooleanField()),
                ('currentlyTakeClients', models.BooleanField()),
                ('licensure', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CounselingNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionNumber', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('dateOfSession', models.DateField()),
                ('lastEdited', models.DateTimeField(default=django.utils.timezone.now)),
                ('summaryPoints', models.CharField(max_length=200)),
                ('additionalDescription', models.CharField(max_length=200)),
                ('visibility', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EmotionWheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(max_length=200)),
                ('dateTime', models.DateTimeField()),
                ('emotionDescriptorOne', models.CharField(max_length=200)),
                ('emotionDescriptorTwo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HealthAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionNumber', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('sessionType', models.CharField(max_length=200)),
                ('dateTime', models.DateTimeField()),
                ('journalPoints', models.CharField(max_length=200)),
                ('additionalDescription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('people', models.JSONField()),
                ('coreBeliefs', models.JSONField()),
                ('emotions', models.JSONField()),
                ('polarity', models.CharField(max_length=200)),
                ('impactLevel', models.IntegerField()),
                ('storyDescription', models.CharField(max_length=200)),
                ('reauthoredStory', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pathways',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('email', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('race', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=200)),
                ('startDate', models.DateField(verbose_name='Start Date')),
                ('lastSession', models.DateField(verbose_name='Last Session Date')),
                ('numOfSessions', models.IntegerField()),
                ('activityStatus', models.BooleanField()),
                ('groundingNumber', models.IntegerField()),
                ('messaging', models.BooleanField()),
                ('resources', models.JSONField()),
                ('therapist', models.CharField(max_length=200)),
                ('storyline', models.JSONField()),
                ('personalityAssessments', models.CharField(max_length=200)),
                ('groundingExercises', models.CharField(max_length=200)),
                ('storylineToolkit', models.CharField(max_length=200)),
                ('genogram', models.CharField(max_length=200)),
                ('goals', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('numberOfLocations', models.IntegerField()),
                ('percentageOfLicensed', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PracticeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionNumber', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('timesPerDay', models.IntegerField()),
                ('timesPerWeek', models.IntegerField()),
                ('practiceTool', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PreSessionCheckIns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionDate', models.DateField()),
                ('feeling', models.CharField(max_length=200)),
                ('progressRating', models.IntegerField()),
                ('bodyScan', models.CharField(max_length=200)),
                ('importantDescription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safePeople', models.JSONField()),
                ('biggestTrigger', models.JSONField()),
                ('calmDown', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
