# Generated by Django 4.0.5 on 2022-07-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storylineapp', '0003_client_delete_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='firstName',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='client',
            name='lastName',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='profession',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='race',
            field=models.TextField(default=''),
        ),
    ]
