# Generated by Django 4.0.5 on 2022-07-09 23:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storylineapp', '0004_remove_client_name_client_firstname_client_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='lastSession',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='client',
            name='startDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
