# Generated by Django 4.0.5 on 2022-07-09 23:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storylineapp', '0005_alter_client_lastsession_alter_client_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='lastSession',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
