# Generated by Django 4.0.5 on 2022-07-09 23:29

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('storylineapp', '0006_alter_client_lastsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='activityStatus',
            field=models.BooleanField(default=sqlalchemy.sql.expression.true),
        ),
        migrations.AlterField(
            model_name='client',
            name='numOfSessions',
            field=models.IntegerField(default=0),
        ),
    ]
