# Generated by Django 4.0.5 on 2022-07-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storylineapp', '0007_alter_client_activitystatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='activityStatus',
            field=models.BooleanField(default=True),
        ),
    ]
