# Generated by Django 4.0.5 on 2022-07-09 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storylineapp', '0008_alter_client_activitystatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='therapist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
