# Generated by Django 4.0.5 on 2022-07-10 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storylineapp', '0009_alter_client_therapist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='firstName',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('nonbinary', 'Non-Binary'), ('prefernottosay', 'Prefer Not To Say')], default='female', max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='lastName',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='profession',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='race',
            field=models.CharField(choices=[('American Indian or Alaska Native', 'American Indian or Alaska Native'), ('Asian', 'Asian'), ('Black or African American', 'Black or African American'), ('Native Hawaiian or Other Pacific Islander', 'Native Hawaiian or Other Pacific Islander'), ('White', 'White'), ('Other', 'Other')], default='White', max_length=200),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
